### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by fubuloubu** [brownie-mix/metacoin-mix#1]
Just did the following:

```bash
$ git clone https://github.com/brownie-mix/metacoin-mix.git
$ cd metacoin-mix
$ pip install eth-brownie
$ brownie bake metacoin
Traceback (most recent call last):
  File "/home/bryant/.pyenv/versions/brownie/bin/brownie", line 7, in <module>
    from brownie.cli.__main__ import main
  File "/home/bryant/.pyenv/versions/3.7.2/envs/brownie/lib/python3.7/site-packages/brownie/__init__.py", line 3, in <module>
    from brownie.network import (
  File "/home/bryant/.pyenv/versions/3.7.2/envs/brownie/lib/python3.7/site-packages/brownie/network/__init__.py", line 5, in <module>
    from .web3 import web3
  File "/home/bryant/.pyenv/versions/3.7.2/envs/brownie/lib/python3.7/site-packages/brownie/network/web3.py", line 3, in <module>
    from web3 import (
ModuleNotFoundError: No module named 'web3'
```

Should add `web3` to the production `brownie` package

**Comment by iamdefinitelyahuman** [comment]
Related to HyperLink-Technology/brownie#70, there was a missing empty line in requirements.txt - fixed with pypi release 1.0.0b2
